[pytest]
filterwarnings =
    # httplib2 uses deprecated pyparsing methods - waiting for upstream fix
    # See: https://github.com/httplib2/httplib2/issues/
    ignore::DeprecationWarning:httplib2.auth
